version: '3.5'

services:
  bot:
    image: wilsonthewolf/isfb
    container_name: isfb
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - 3000:3000
